# Generated by Django 3.2.6 on 2021-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='prefabdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('picture', models.IntegerField(default=0)),
                ('picture_extention', models.CharField(default='png', max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('static_file_names', models.TextField(default='')),
                ('user', models.CharField(default='default_user', max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('path', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tocken', models.CharField(max_length=255)),
                ('prefabs', models.TextField(default='')),
            ],
        ),
    ]
