# Generated by Django 3.2.6 on 2021-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefabdata',
            name='user_like_putin',
            field=models.TextField(default='10'),
        ),
    ]
