# Generated by Django 3.2.6 on 2021-08-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefabdata',
            name='component',
        ),
    ]
